---
name: Build Jekyll Site in Docker

on:
  push:
    branches:
      - main

concurrency:
  group: build
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: docker.io/berkes/jekyll:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: 'jekyll'

    - name: Run Jekyll build
      run: |
        cd jekyll
        bundle exec rake build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: site.zip
        path: jekyll/build

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: site.zip

    - name: Copy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: deploy
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: "./*"
        target: "/u/apps/berkes/tmp/deploy_content"

    - name: Atomic Swap
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: deploy
        key: ${{ secrets.SSH_KEY }}
        script: |
          export ds=$(date +"%Y%m%d%H%M%S")
          # Make a new version dir
          mkdir /u/apps/berkes/releases/${ds}
          # Add to the new version
          mv /u/apps/berkes/tmp/deploy_content/ /u/apps/berkes/releases/${ds}/public/
          # update the current symlink
          rm /u/apps/berkes/current && ln -s /u/apps/berkes/releases/${ds}/ /u/apps/berkes/current
